modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/TagnumElite/ProjectE-Integration/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = "https://raw.githubusercontent.com/TagnumElite/ProjectE-Integration/1.20.x/update.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/projecte-integration"
# logoFile="examplemod.png"
credits = "Thanks to ProjectE team for ProjectE"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "projecte"
mandatory = true
versionRange = "[PE1.0.1,)"

[[dependencies.${mod_id}]]
modId = "alchemistry"
mandatory = false
versionRange = "[1.20.1-2.3,)"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
