modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/TagnumElite/ProjectE-Integration/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = "https://raw.githubusercontent.com/TagnumElite/ProjectE-Integration/1.20.x/update.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/projecte-integration"
# logoFile="examplemod.png"
credits = "Thanks to ProjectE team for ProjectE"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "projecte"
mandatory = true
versionRange = "[PE1.0.0B,)"

[[dependencies.${mod_id}]]
modId = "alchemistry"
mandatory = false
versionRange = "[1.19.2-2.2,)"

[[dependencies.${mod_id}]]
modId = "chipped"
mandatory = false
versionRange = "[3.0.4,)"

#[[dependencies.${mod_id}]]
#modId = "create"
#mandatory = false
#versionRange = "[0.5.0,)"

#[[dependencies.${mod_id}]]
#modId = "farmersdelight"
#mandatory = false
#versionRange = "[1.18.2-1.1.2,)"

#[[dependencies.${mod_id}]]
#modId = "pneumaticcraft"
#mandatory = false
#versionRange = "[1.18.2-3.3.0,)"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
